CREATE TABLE TB_PESSOA (
	ID_PESSOA INT NOT NULL, --  Identificação sequêncial de Pessoa
	TX_HASH VARCHAR(50), -- Algoritimo ultilizando para garanit a integridade dos dados
	DT_NASCIMENTO DATE NOT NULL, -- Data de nascimento para criação do Hash
	NM_GENITOR VARCHAR(100) NOT NULL, -- Nome da mae para criação do Hash
	ST_EMBRIAO char(1) DEFAULT '1', -- Identificação para criaçao do Hash
	PRIMARY KEY (ID_PESSOA),
	CONSTRAINT UK_PESSOA_TX_HASH UNIQUE (TX_HASH)
	); 
CREATE SEQUENCE SQ_PESSOA
	  MINVALUE 1
	  START WITH 1
	  INCREMENT BY 1
	  NOCACHE;
CREATE TABLE TB_MUNICIPIO(
	ID_MUNICIPIO INT NOT NULL ,--  Identificação sequêncial de Municipio
 	NM_MUNICIPIO VARCHAR (50),
 	PRIMARY KEY (ID_MUNICIPIO),
 	CONSTRAINT uk_municipio_nmMunicipio UNIQUE (NM_MUNICIPIO)
 	);
CREATE SEQUENCE SQ_MUNICIPIO
	 MINVALUE 1
	 START WITH 1
	 INCREMENT BY 1
	 NOCACHE;
	  
CREATE TABLE TB_TIPO_GERAL (
	ID_TIPO_GERAL INT NOT NULL,
	NM_TIPO_GERAL VARCHAR (100) NOT NULL,
	NM_CHAVE VARCHAR (100) NOT NULL,
	ST_PADRAO INT NOT NULL,
	TX_PARAMETRO BLOB, 
	ST_ATIVO char(1) DEFAULT '1' NOT NULL,
	PRIMARY KEY (ID_TIPO_GERAL),
	CONSTRAINT UK_TIPOGERAL_NM_CHAVE UNIQUE (NM_CHAVE)
	 );
 CREATE SEQUENCE SQ_TIPOGERAL
	  MINVALUE 1
	  START WITH 1
	  INCREMENT BY 1
	  NOCACHE;	
	 
CREATE TABLE TB_PESSOA_ENDERECO(
	 ID_PESSOA_ENDERECO INT NOT NULL,
	 ID_PESSOA INT NOT NULL ,
	 ID_TIPO_LOGADOURO INT NOT NULL,
	 ID_MUNICIPIO INT NOT NULL,
	 NM_LOGADOURO VARCHAR(250) NOT NULL,
	 NM_COMPLEMENTO VARCHAR(30) NOT NULL,
	 NM_NUMERO VARCHAR(20) NOT NULL,
	 NM_BAIRRO VARCHAR (100) NOT NULL,
	 NM_CEP INT NOT NULL,
	 PRIMARY KEY (ID_PESSOA_ENDERECO),
	 CONSTRAINT FK_PESSOA_ENDERECO FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	 CONSTRAINT FK_PESSOA_ENDERECO_TIPOGERAL FOREIGN KEY (ID_TIPO_LOGADOURO) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL),
	 CONSTRAINT FK_PESSOA_ENDERECO_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES TB_MUNICIPIO(ID_MUNICIPIO)
	 );
CREATE SEQUENCE SQ_PESSOAENDERECO
	  MINVALUE 1
	  START WITH 1
	  INCREMENT BY 1
	  NOCACHE;
	  	
CREATE TABLE TB_PESSOA_DOCUMENTO(
	 ID_PESSOA_DOCUMENTO INT NOT NULL,
	 ID_PESSOA INT NOT NULL ,
	 ID_TIPO_DOCUMENTO INT NOT NULL,
	 VR_DOCUMENTO VARCHAR(100) NOT NULL,
	 DT_EMISSAO DATE NOT NULL,
	 NM_ORGAO_EMISSOR VARCHAR (100),
	 DS_SERIE VARCHAR (50) NOT NULL,
	 PRIMARY KEY (ID_PESSOA_DOCUMENTO),
	 CONSTRAINT FK_PESSOA_DOCUMENTO FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	 CONSTRAINT FK_PESSOA_DOCUMENTO_TIPOGERAL FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL)
	 );
CREATE SEQUENCE SQ_PESSOADOCUMENTO
	  MINVALUE 1
	  START WITH 1
	  INCREMENT BY 1
	  NOCACHE;	
 
 CREATE TABLE TB_PESSOA_NOME(
	ID_PESSOA_NOME INT NOT NULL,
	ID_PESSOA INT NOT NULL,
	ID_PESSOA_DOCUMENTO INT NOT NULL,
	NM_PESSOA VARCHAR (250) NOT NULL,
	PRIMARY KEY (ID_PESSOA_NOME),
	CONSTRAINT FK_PESSOA_NOME FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	CONSTRAINT FK_PESSOA_NOME_DOCUMENTO FOREIGN KEY (ID_PESSOA_DOCUMENTO) REFERENCES TB_PESSOA_DOCUMENTO(ID_PESSOA_DOCUMENTO)
	 );
 CREATE SEQUENCE SQ_PESSOA_NOME
	    MINVALUE 1
	    START WITH 1
	    INCREMENT BY 1
	    NOCACHE;	    
	    
CREATE TABLE TB_PESSOA_CONTATOS(
	  ID_PESSOA_CONTATOS INT NOT NULL,
	  ID_PESSOA INT NOT NULL,
	  ID_TIPO_CONTATO INT NOT NULL,
	  NM_CONTATO VARCHAR (250) NOT NULL,
	  DS_CONTATO VARCHAR (100),
	  PRIMARY KEY (ID_PESSOA_CONTATOS),
	  CONSTRAINT FK_PESSOA_CONTATO FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	  CONSTRAINT FK_PESSOA_CONTATOS_TIPO_GERAL FOREIGN KEY (ID_TIPO_CONTATO) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL)
	   );
	  
CREATE SEQUENCE SQ_PESSOA_CONTATOS
	   MINVALUE 1
	   START WITH 1
	   INCREMENT BY 1
	   NOCACHE;
	     
CREATE TABLE TB_DEPENDECIA(
	   ID_DEPENDENCIA INT NOT NULL,
	   ID_PESSOA INT NOT NULL,
	   ID_PESSOA_DEPENDENTE INT NOT NULL,
	   ID_TIPO_DEPENDENCIA INT NOT NULL,
	   PRIMARY KEY (ID_DEPENDENCIA),
	   CONSTRAINT 	UK_PESSOA_DEPENDENTE  UNIQUE (ID_PESSOA_DEPENDENTE),
	   CONSTRAINT FK_PESSOA_CONTATOS FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	   CONSTRAINT FK_PESSOA_DEPENDENTE FOREIGN KEY (ID_PESSOA_DEPENDENTE) REFERENCES TB_PESSOA(ID_PESSOA),
	   CONSTRAINT FK_PESSOA_DEPENDENCIA_TIPO_GERAL FOREIGN KEY (ID_TIPO_DEPENDENCIA) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL)
	    );
CREATE SEQUENCE SQ_DEPENDENCIA
	     MINVALUE 1
	     START WITH 1
	     INCREMENT BY 1
	     NOCACHE;
	    
CREATE TABLE TB_DIC_NOME(
	   	ID_DIC_NOME INT NOT NULL,
	   	ID_TIPO_SEXO INT NOT NULL,
	   	TX_NOME VARCHAR(100) NOT NULL,
	   	PRIMARY KEY (ID_DIC_NOME),
	   	CONSTRAINT UK_DIC_NOME UNIQUE (TX_NOME),
	   	CONSTRAINT FK_DIC_NOME_TIPO_GERAL FOREIGN KEY (ID_TIPO_SEXO) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL)
	    );
 CREATE SEQUENCE SQ_DIC_NOME
		  MINVALUE 1
		  START WITH 1
		  INCREMENT BY 1
		  NOCACHE;
		   
 CREATE TABLE TB_DIC_NOME_FAMILIA(
		  ID_DIC_NOME_FAMILIA INT NOT NULL,
		  TX_NOME_FAMILIA VARCHAR (100) NOT NULL,
		  PRIMARY KEY (ID_DIC_NOME_FAMILIA),
	   	  CONSTRAINT 	UK_DIC_NOME_FAMILIA UNIQUE (TX_NOME_FAMILIA)
		 );
CREATE SEQUENCE SQ_DIC_NOME_FAMILIA
		  MINVALUE 1
		  START WITH 1
		  INCREMENT BY 1
		  NOCACHE;
		   
CREATE TABLE TB_PESSOA_SITUACAO(
		ID_PESSOA_SITUACAO INT NOT NULL,
		ID_PESSOA INT NOT NULL,
		ID_TIPO_SITUACAO INT NOT NULL,
		DT_SITUACAO DATE NOT NULL,
		PRIMARY KEY (ID_PESSOA_SITUACAO),
		CONSTRAINT FK_PESSOA_SITUACAO FOREIGN KEY (ID_TIPO_SITUACAO) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL)
		);
CREATE SEQUENCE SQ_PESSOA_SITUACAO
		   MINVALUE 1
		   START WITH 1
		   INCREMENT BY 1
		   NOCACHE;
		   
CREATE TABLE TB_TIPO_GERAL_FILTRO(
		  ID_TIPO_GERAL_FILTRO INT NOT NULL,
		  NM_FILTRO VARCHAR(100) NOT NULL,
		  PRIMARY KEY (ID_TIPO_GERAL_FILTRO)
		);
CREATE SEQUENCE SQ_TIPO_GERAL_FILTRO
		  MINVALUE 1
		  START WITH 1
		  INCREMENT BY 1
		   NOCACHE;
		   
CREATE TABLE RL_TIPO_GERAL_TIPO_GERAL_FILTRO(
		    ID_TIPO_GERAL_TIPO_GERAL_FILTRO INT NOT NULL,
		    ID_TIPO_GERAL INT NOT NULL,
		    ID_TIPO_GERAL_FILTRO INT NOT NULL,
		    PRIMARY KEY (ID_TIPO_GERAL_TIPO_GERAL_FILTRO),
		    CONSTRAINT 	UK_RL_TIPOGERAL_TIPOGERALFILTRO UNIQUE (ID_TIPO_GERAL, ID_TIPO_GERAL_FILTRO),
		    CONSTRAINT FK_TIPO_GERAL_TIPO_GERAL_FILTRO FOREIGN KEY (ID_TIPO_GERAL) REFERENCES TB_TIPO_GERAL(ID_TIPO_GERAL),
		    CONSTRAINT FK_TIPO_GERAL_FILTRO FOREIGN KEY (ID_TIPO_GERAL_FILTRO) REFERENCES TB_TIPO_GERAL_FILTRO(ID_TIPO_GERAL_FILTRO)
		 );
CREATE SEQUENCE SQ_TIPO_GERAL_TIPO_GERAL_FILTRO
		    MINVALUE 1
		    START WITH 1
		    INCREMENT BY 1
		    NOCACHE;	  
		    
		   
		   
		   

		   

		   
		   
		   
