-- DROPS DAS TABELAS
DROP TABLE SYS_PESSOA.TB_PESSOA;
DROP TABLE SYS_PESSOA.TB_MUNICIPIO;
DROP TABLE SYS_PESSOA.TB_TIPO_GERAL;
DROP TABLE SYS_PESSOA.TB_PESSOA_ENDERECO;
DROP TABLE SYS_PESSOA.TB_PESSOA_dOCUMENTO;
DROP TABLE SYS_PESSOA.TB_PESSOA_NOME;
DROP TABLE SYS_PESSOA.TB_PESSOA_CONTATOS;
DROP TABLE SYS_PESSOA.TB_PESSOA_SITUACAO;
DROP TABLE SYS_PESSOA.TB_DEPENDENCIA;
DROP TABLE SYS_PESSOA.TB_DIC_NOME;
DROP TABLE SYS_PESSOA.TB_DIC_NOME_FAMILIA;
DROP TABLE SYS_PESSOA.TB_TIPO_GERAL_FILTRO;
DROP TABLE SYS_PESSOA.RL_TIPO_GERAL_TIPO_GERAL_FILTRO;

-- DROPS SEQUENCE
DROP SEQUENCE SYS_PESSOA.SQ_PESSOA;
DROP SEQUENCE SYS_PESSOA.SQ_MUNICIPIO;
DROP SEQUENCE SYS_PESSOA.SQ_TIPOGERAL;
DROP SEQUENCE SYS_PESSOA.SQ_PESSOAENDERECO;
DROP SEQUENCE SYS_PESSOA.SQ_PESSOADOCUMENTO;
DROP SEQUENCE SYS_PESSOA.SQ_PESSOA_NOME;
DROP SEQUENCE SYS_PESSOA.SQ_PESSOA_CONTATOS;
DROP SEQUENCE SYS_PESSOA.SQ_DEPENDENCIA;
DROP SEQUENCE SYS_PESSOA.SQ_DIC_NOME;
DROP SEQUENCE SYS_PESSOA.SQ_DIC_NOME_FAMILIA;
DROP SEQUENCE SYS_PESSOA.SQ_PESSOA_SITUACAO;
DROP SEQUENCE SYS_PESSOA.SQ_TIPO_GERAL_FILTRO;
DROP SEQUENCE SYS_PESSOA.SQ_TIPO_GERAL_TIPO_GERAL_FILTRO;









