USE pessoa;
ALTER TABLE pessoa.tb_dependencia DROP FOREIGN KEY fkDependencia_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_dependencia DROP FOREIGN KEY fkPessoaDependente_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_dependencia DROP FOREIGN KEY fkTipoDependencia_tbTipoGeral_idTipoGeral;
ALTER TABLE pessoa.tb_dic_nome DROP FOREIGN KEY fkDic_Nome_tb_Tipogeral_idTipoGeral;
ALTER TABLE pessoa.tb_pessoa_endereco DROP FOREIGN KEY fkPessoa_Endereco_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_pessoa_endereco DROP FOREIGN KEY fkPessoa_Endereco_tbTipoGeral_idTipoGeral;
ALTER TABLE pessoa.tb_pessoa_endereco DROP FOREIGN KEY fkPessoa_Endereco_tbMunicipio_idMunicipio;
ALTER TABLE pessoa.tb_pessoa_documento DROP FOREIGN KEY fkPessoa_Documento_tbTipoGeral_idTipoGeral;
ALTER TABLE pessoa.tb_pessoa_documento DROP FOREIGN KEY fkPessoa_Documento_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_pessoa_nome DROP FOREIGN KEY fkPessoa_Nome_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_pessoa_nome DROP FOREIGN KEY fkPessoa_Nome_tbPessoaDocumento_idPessoaDocumento;
ALTER TABLE pessoa.tb_pessoa_contatos DROP FOREIGN KEY fkPessoa_Contatos_tbPessoa_idPessoa;
ALTER TABLE pessoa.tb_pessoa_contatos DROP FOREIGN KEY fkPessoa_Contatos_tbTipoGeral_idTipoGeral;
USE pessoa;
DROP TABLE IF EXISTS `tb_pessoa_endereco`;
DROP TABLE IF EXISTS `tb_pessoa_documento`;
DROP TABLE IF EXISTS `tb_pessoa_nome`;
DROP TABLE IF EXISTS `tb_pessoa_contatos`;
DROP TABLE IF EXISTS `tb_municipio`;
DROP TABLE IF EXISTS `tb_dependencia`;
DROP TABLE IF EXISTS `tb_dic_nome`;
DROP TABLE IF EXISTS `tb_dic_nome_Familia`;
DROP TABLE IF EXISTS `tb_tipogeral`;
DROP TABLE IF EXISTS `tb_pessoa`;
DROP TRIGGER IF EXISTS `TgrPreenchimentoHashPessoa`;
DROP TRIGGER IF EXISTS `TgrPreenchimentoHashPessoaNome`;
